### ISSUE TITLE
How should I do to show Text in konva canvas?

### ISSUE THREAD

**Issue by wfsm** [konvajs/react-konva#228]
I put a Text into a Layer, like,
`<Layer>
            <Text x={20} y={20} text="aaa"/>
            <Text x={40} y={20} text="bbb"/>
            <Text x={60} y={20} text="ccc"/>
</Layer>`
but got **Text components are not supported for now in ReactKonva.**
I change Text component to Shape, like,
`<Layer>
            <Shape x={20} y={20}>aaa</Shape>
            <Shape x={40} y={20}>bbb</Shape>
            <Shape x={60} y={20}>ccc</Shape>
</Layer>`
got the same error.
How should I do to show Text in konva canvas?

By the way, sometimes Text component works, without any error.

**Comment by lavrton** [comment]
The first code example is correct. But I guess spaces between tags are inserted as " " strings into components. I published a new version with a more clear error message.
This should work ok:
```js
<Layer>
  <Text x={20} y={20} text="aaa"/>
  <Text x={40} y={20} text="bbb"/>
  <Text x={60} y={20} text="ccc"/>
</Layer>
```

**Comment by ivoiv** [comment]
Hi! Thank you so much for creating React Konva, it's a really amazing tool to work with.

Regarding the issue, I still get the same message as the user above when I incorrectly use the Text component like this
<Text>SomeText</Text> 
Text components are not supported for now in ReactKonva. You text is: "SomeText"

Only after I googled around did I find this issue showing me I was using it incorrectly.
Maybe you forgot to update the error message?

I am using "react-konva": "^16.13.0-3",

**Comment by lavrton** [comment]
> Text components are not supported for now in ReactKonva. You text is: "SomeText"

That is an error/warning message.
